calian_gnss:
  gps:
    ros__parameters:
      use_corrections: True
      config_path: 'src/calian_gnss_ros2/pointperfect_files/ucenter-config.json'
      region: 'us'

calian_gnss:                  
  gps_publisher:
    ros__parameters:
      use_corrections: True
      config_path: 'src/calian_gnss_ros2/pointperfect_files/ucenter-config.json'
      region: 'us'

calian_gnss:
  base:
    ros__parameters:
      use_corrections: True
      config_path: 'src/calian_gnss_ros2/pointperfect_files/ucenter-config.json'
      region: 'us'

calian_gnss:
  rover:
    ros__parameters:
      use_corrections: False